# -*- coding: utf-8 -*-
"""Untitled41.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iDgzVIkphWoAfrRvhXObWkItJfBQe1FY
"""


from datasets import load_dataset
import argparse
import os
import random
from dataclasses import dataclass

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from datasets import load_dataset
from tokenizers import ByteLevelBPETokenizer
from torch.optim import AdamW
from torch.utils.data import DataLoader
from tqdm.auto import tqdm
from transformers import PreTrainedTokenizerFast

try:
    import wandb
except ImportError:
    wandb = None


def set_seed(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)


class AttentionHead(nn.Module):
    def __init__(self, embed_dim: int, head_dim: int):
        super().__init__()
        self.q = nn.Linear(embed_dim, head_dim)
        self.k = nn.Linear(embed_dim, head_dim)
        self.v = nn.Linear(embed_dim, head_dim)

    def forward(self, hidden_state: torch.Tensor) -> torch.Tensor:
        return self._attention(
            self.q(hidden_state),
            self.k(hidden_state),
            self.v(hidden_state),
        )

    def _attention(self, query: torch.Tensor, key: torch.Tensor, value: torch.Tensor) -> torch.Tensor:
        attn_scores = torch.matmul(query, key.transpose(-2, -1)) / (key.size(-1) ** 0.5)
        seq_length = query.size(1)
        causal_mask = torch.triu(torch.ones(seq_length, seq_length, device=query.device), diagonal=1).bool()
        attn_scores = attn_scores.masked_fill(causal_mask, -1e10)
        attn_weights = F.softmax(attn_scores, dim=-1)
        return torch.matmul(attn_weights, value)


class MultiHeadAttention(nn.Module):
    def __init__(self, config: "GPTConfig"):
        super().__init__()
        embed_dim = config.hidden_size
        num_heads = config.num_attention_heads
        head_dim = embed_dim // num_heads
        self.heads = nn.ModuleList([AttentionHead(embed_dim, head_dim) for _ in range(num_heads)])
        self.output_linear = nn.Linear(embed_dim, embed_dim)

    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:
        head_outputs = [head(hidden_states) for head in self.heads]
        concatenated = torch.cat(head_outputs, dim=-1)
        return self.output_linear(concatenated)


class FeedForward(nn.Module):
    def __init__(self, config: "GPTConfig"):
        super().__init__()
        self.linear1 = nn.Linear(config.hidden_size, config.intermediate_size)
        self.linear2 = nn.Linear(config.intermediate_size, config.hidden_size)
        self.activation = nn.GELU()
        self.dropout = nn.Dropout(config.hidden_dropout_prob)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = self.linear1(x)
        x = self.activation(x)
        x = self.dropout(x)
        x = self.linear2(x)
        return x


class TransformerBlock(nn.Module):
    def __init__(self, config: "GPTConfig"):
        super().__init__()
        self.attention = MultiHeadAttention(config)
        self.layer_norm1 = nn.LayerNorm(config.hidden_size)
        self.layer_norm2 = nn.LayerNorm(config.hidden_size)
        self.feed_forward = FeedForward(config)
        self.dropout = nn.Dropout(config.hidden_dropout_prob)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        residual = x
        x = self.layer_norm1(x)
        x = self.attention(x)
        x = self.dropout(x)
        x = x + residual

        residual = x
        x = self.layer_norm2(x)
        x = self.feed_forward(x)
        x = self.dropout(x)
        x = x + residual
        return x


@dataclass
class GPTConfig:
    vocab_size: int = 30000
    hidden_size: int = 256
    num_hidden_layers: int = 4
    num_attention_heads: int = 4
    intermediate_size: int = 512
    hidden_dropout_prob: float = 0.1
    max_position_embeddings: int = 128


class SimpleLLM(nn.Module):
    def __init__(self, config: GPTConfig):
        super().__init__()
        self.config = config
        self.token_embeddings = nn.Embedding(config.vocab_size, config.hidden_size)
        self.position_embeddings = nn.Embedding(config.max_position_embeddings, config.hidden_size)
        self.transformer_blocks = nn.ModuleList([TransformerBlock(config) for _ in range(config.num_hidden_layers)])
        self.layer_norm = nn.LayerNorm(config.hidden_size)
        self.output = nn.Linear(config.hidden_size, config.vocab_size, bias=False)
        self.apply(self._init_weights)

    def _init_weights(self, module: nn.Module) -> None:
        if isinstance(module, (nn.Linear, nn.Embedding)):
            module.weight.data.normal_(mean=0.0, std=0.02)
            if isinstance(module, nn.Linear) and module.bias is not None:
                module.bias.data.zero_()
        elif isinstance(module, nn.LayerNorm):
            module.bias.data.zero_()
            module.weight.data.fill_(1.0)

    def forward(self, input_ids: torch.Tensor) -> torch.Tensor:
        batch_size, seq_length = input_ids.size()
        token_embeds = self.token_embeddings(input_ids)
        position_ids = torch.arange(seq_length, dtype=torch.long, device=input_ids.device)
        position_ids = position_ids.unsqueeze(0).expand(batch_size, -1)
        position_embeds = self.position_embeddings(position_ids)

        x = token_embeds + position_embeds
        for block in self.transformer_blocks:
            x = block(x)
        x = self.layer_norm(x)
        return self.output(x)


def train_tokenizer(dataset, tokenizer_dir: str, vocab_size: int) -> PreTrainedTokenizerFast:
    os.makedirs(tokenizer_dir, exist_ok=True)
    tokenizer = ByteLevelBPETokenizer()

    def get_training_corpus():
        for i in range(len(dataset["train"])):
            text = dataset["train"][i]["text"]
            if text.strip():
                yield text

    tokenizer.train_from_iterator(
        get_training_corpus(),
        vocab_size=vocab_size,
        min_frequency=2,
        special_tokens=["<s>", "<pad>", "</s>", "<unk>", "<mask>"],
    )

    tokenizer.save_model(tokenizer_dir)
    tokenizer_json_path = os.path.join(tokenizer_dir, "tokenizer.json")
    tokenizer.save(tokenizer_json_path)

    fast_tokenizer = PreTrainedTokenizerFast(tokenizer_file=tokenizer_json_path)
    fast_tokenizer.pad_token = "<pad>"
    fast_tokenizer.eos_token = "</s>"
    fast_tokenizer.bos_token = "<s>"
    fast_tokenizer.unk_token = "<unk>"
    return fast_tokenizer


def tokenize_dataset(dataset, tokenizer: PreTrainedTokenizerFast, max_length: int):
    def tokenize_function(examples):
        return tokenizer(
            examples["text"],
            padding="max_length",
            truncation=True,
            max_length=max_length,
        )

    tokenized = dataset.map(tokenize_function, batched=True, remove_columns=["text"])
    tokenized.set_format(type="torch", columns=["input_ids", "attention_mask"])
    return tokenized


def compute_causal_lm_loss(logits: torch.Tensor, input_ids: torch.Tensor, pad_token_id: int) -> torch.Tensor:
    shift_logits = logits[:, :-1, :].contiguous()
    shift_labels = input_ids[:, 1:].contiguous()
    return F.cross_entropy(
        shift_logits.view(-1, shift_logits.size(-1)),
        shift_labels.view(-1),
        ignore_index=pad_token_id,
    )


def evaluate(model: nn.Module, dataloader: DataLoader, device: torch.device, pad_token_id: int) -> float:
    model.eval()
    total_loss = 0.0
    total_tokens = 0

    with torch.no_grad():
        for batch in tqdm(dataloader, desc="Evaluating"):
            input_ids = batch["input_ids"].to(device)
            logits = model(input_ids)

            shift_logits = logits[:, :-1, :].contiguous()
            shift_labels = input_ids[:, 1:].contiguous()

            loss_sum = F.cross_entropy(
                shift_logits.view(-1, shift_logits.size(-1)),
                shift_labels.view(-1),
                ignore_index=pad_token_id,
                reduction="sum",
            )

            non_pad_tokens = shift_labels.ne(pad_token_id).sum().item()
            total_loss += loss_sum.item()
            total_tokens += non_pad_tokens

    if total_tokens == 0:
        return float("inf")
    perplexity = torch.exp(torch.tensor(total_loss / total_tokens))
    return perplexity.item()


def main() -> None:
    parser = argparse.ArgumentParser(description="Train a small GPT-like model on WikiText-2")
    parser.add_argument("--output-dir", default="artifacts")
    parser.add_argument("--tokenizer-dir", default="artifacts/tokenizer")
    parser.add_argument("--batch-size", type=int, default=16)
    parser.add_argument("--epochs", type=int, default=5)
    parser.add_argument("--lr", type=float, default=3e-4)
    parser.add_argument("--weight-decay", type=float, default=0.01)
    parser.add_argument("--num-workers", type=int, default=2)
    parser.add_argument("--max-length", type=int, default=128)
    parser.add_argument("--vocab-size", type=int, default=30000)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--use-wandb", action="store_true")
    parser.add_argument("--wandb-project", default="simple-llm")
    args = parser.parse_args()

    set_seed(args.seed)
    os.makedirs(args.output_dir, exist_ok=True)

    dataset = load_dataset("wikitext", "wikitext-2-raw-v1")
    print(f"Train set size: {len(dataset['train'])}")
    print(f"Sample text: {dataset['train'][0]['text'][:200]}")

    tokenizer = train_tokenizer(dataset, args.tokenizer_dir, args.vocab_size)
    tokenized_datasets = tokenize_dataset(dataset, tokenizer, args.max_length)

    config = GPTConfig(
        vocab_size=tokenizer.vocab_size,
        hidden_size=256,
        num_hidden_layers=4,
        num_attention_heads=4,
        intermediate_size=512,
        max_position_embeddings=args.max_length,
    )

    model = SimpleLLM(config)
    print(f"Model parameters: {sum(p.numel() for p in model.parameters())}")

    train_dataloader = DataLoader(
        tokenized_datasets["train"],
        batch_size=args.batch_size,
        shuffle=True,
        num_workers=args.num_workers,
        pin_memory=torch.cuda.is_available(),
    )
    eval_dataloader = DataLoader(
        tokenized_datasets["validation"],
        batch_size=args.batch_size,
        num_workers=args.num_workers,
        pin_memory=torch.cuda.is_available(),
    )

    optimizer = AdamW(model.parameters(), lr=args.lr, weight_decay=args.weight_decay)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model.to(device)
    print(f"Using device: {device}")

    wandb_enabled = args.use_wandb and wandb is not None
    if args.use_wandb and wandb is None:
        print("W&B requested, but package is not installed. Continuing without W&B logging.")
    if wandb_enabled:
        wandb.init(project=args.wandb_project)

    model.train()
    for epoch in range(args.epochs):
        epoch_loss = 0.0
        progress_bar = tqdm(train_dataloader, desc=f"Epoch {epoch + 1}/{args.epochs}")

        for batch in progress_bar:
            input_ids = batch["input_ids"].to(device)
            logits = model(input_ids)
            loss = compute_causal_lm_loss(logits, input_ids, tokenizer.pad_token_id)

            optimizer.zero_grad(set_to_none=True)
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
            optimizer.step()

            epoch_loss += loss.item()
            progress_bar.set_postfix({"loss": f"{loss.item():.4f}"})
            if wandb_enabled:
                wandb.log({"batch_loss": loss.item()})

        avg_epoch_loss = epoch_loss / max(len(train_dataloader), 1)
        print(f"Epoch {epoch + 1} loss: {avg_epoch_loss:.4f}")
        if wandb_enabled:
            wandb.log({"epoch": epoch + 1, "epoch_loss": avg_epoch_loss})

        checkpoint_path = os.path.join(args.output_dir, f"model_checkpoint_epoch_{epoch + 1}.pt")
        torch.save(
            {
                "epoch": epoch + 1,
                "model_state_dict": model.state_dict(),
                "optimizer_state_dict": optimizer.state_dict(),
                "loss": avg_epoch_loss,
                "config": config,
                "tokenizer_dir": args.tokenizer_dir,
            },
            checkpoint_path,
        )

    final_model_path = os.path.join(args.output_dir, "simple_llm_final.pt")
    torch.save(model.state_dict(), final_model_path)

    perplexity = evaluate(model, eval_dataloader, device, tokenizer.pad_token_id)
    print(f"Validation perplexity: {perplexity:.2f}")
    if wandb_enabled:
        wandb.log({"perplexity": perplexity})
        wandb.finish()


if __name__ == "__main__":
    main()